# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcee < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.0/emcee_Darwin_x86_64.tar.gz"
      sha256 "48765a35eaab256503b43e88cd244c0819cafc60485c41ad4c6bec4667ca783d"

      def install
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.0/emcee_Darwin_arm64.tar.gz"
      sha256 "7f0423016240b9bac25ab3c1ba3f85d1b03f0f877a085574b8aadef503f75a6d"

      def install
        bin.install "emcee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.0/emcee_Linux_x86_64.tar.gz"
        sha256 "8444a62f5d99071bb03829cc9e2c705bd45e42d2fbc0b0e0b1ad2e9168c6f377"

        def install
          bin.install "emcee"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.0/emcee_Linux_arm64.tar.gz"
        sha256 "474e686de6dc75568c6373716d8761d4d352790c618b160bc44122084781a7d2"

        def install
          bin.install "emcee"
        end
      end
    end
  end
end
