# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcee < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.2.0/emcee_Darwin_x86_64.tar.gz"
      sha256 "1ff4503cb4f7b1bc889667e46ca11c424295e72d24bae86c2be25d6171ff1292"

      def install
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.2.0/emcee_Darwin_arm64.tar.gz"
      sha256 "bd09792acdd3c46fdeb8e5c980ebe43ac46690fbc5cbe741a4c013eebbdbb4a1"

      def install
        bin.install "emcee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.2.0/emcee_Linux_x86_64.tar.gz"
        sha256 "acea7c9d617b9d3d4c27718eb4d63145f3d3fb076aa91a483805a66f877952b5"

        def install
          bin.install "emcee"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.2.0/emcee_Linux_arm64.tar.gz"
        sha256 "73db851fbc63a41e3ae46d6127866fdc05a4dd4323295c1d5ce8f5f4e143bee8"

        def install
          bin.install "emcee"
        end
      end
    end
  end
end
