# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emcee < Formula
  desc ""
  homepage ""
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.3/emcee_Darwin_x86_64.tar.gz"
      sha256 "15ac5df14e793f5b01a62c361ce4c2dc7c803d38fb2c786d969903e42365d745"

      def install
        bin.install "emcee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.3/emcee_Darwin_arm64.tar.gz"
      sha256 "90e13493105dbe078ac681ee1d7991e9717dc7f3970829eff60416efd3d56a39"

      def install
        bin.install "emcee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.3/emcee_Linux_x86_64.tar.gz"
        sha256 "443d15916663fede21c9984926fe139f68eaeb9f4b136937d8a3c20a5879d550"

        def install
          bin.install "emcee"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/loopwork-ai/emcee/releases/download/v0.4.3/emcee_Linux_arm64.tar.gz"
        sha256 "d62315cadfcb3348e4884cd34873f660fe595d497a8fa3096e6943a6f3e4d4ab"

        def install
          bin.install "emcee"
        end
      end
    end
  end
end
